### ISSUE TITLE
Sample fonts.json request

### ISSUE THREAD

**Issue by okpatil4u** [pdf-rs/pdf_render#7]
What is the structure of fonts.json ? Could you please post a sample fonts.json somewhere ?

I am getting the following error.

```
PDF: STANDARD_FONTS not set. using fonts/ instead.
thread 'main' panicked at 'can't read fonts.json: Os { code: 2, kind: NotFound, message: "No such file or directory" }', render/src/font.rs:55:68
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::expect
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1022:23
   4: pdf_render::font::StandardCache::new
             at /Users/omkarpatil/experiments/ghostscript/pdf_render/render/src/font.rs:55:20
   5: pdf_render::cache::Cache::new
             at /Users/omkarpatil/experiments/ghostscript/pdf_render/render/src/cache.rs:54:18
   6: pdf2image::main
             at ./src/main.rs:37:21
   7: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by s3bk** [comment]
https://github.com/s3bk/pdf_fonts

the font files are from `/usr/share/fonts/type1/gsfonts/` on ubuntu.

**Comment by okpatil4u** [comment]
Thanks dude !
